# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
#before:
#  hooks:
#    # you may remove this if you don't use vgo
#    - go mod download
#    # you may remove this if you don't need go generate
#    - go generate ./...

project_name: go-gitlint
before:
  hooks:
    - go mod download
builds:
  -
    env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: gitlint
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
archive:
  replacements:
    darwin: osx
    386: x86_32
    amd64: x86_64
release:
  name_template: "{{.Tag}}"
  prerelease: auto
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
